version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:641392857770:task-definition/signalr-simple-example-task-definition:1"
        LoadBalancerInfo:
          ContainerName: "signalr-simple-example-container"
          ContainerPort: "80"
        PlatformVersion: "LATEST"